source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'thin', '~>1.6'
gem 'json', '~>1.8'
gem 'sinatra-contrib', '~>1.4'
gem 'nokogiri', '~>1.6'
gem 'json-schema', '~>2.5'
gem 'rest-client', '~>1.8'
gem 'rake'
gem 'sinatra-activerecord'
gem 'shotgun'
gem 'logstash-logger'
gem 'will_paginate', '~>3.0' # Pagination library

# Gatekeeper auth gem
gem 'sinatra-gkauth', '~>0.2.0', path: '../sinatra-gkauth-gem'

group :development do
	gem 'rerun'
	gem 'sqlite3'
end

group :test do
	gem 'rack-test'
	gem 'rspec'
end

group :production do
	gem 'pg'
end

group :doc do
	gem 'yard', '~>0.8'
end
